### ISSUE TITLE
Add Impossible Omega II Raids

### ISSUE THREAD

**Issue by FabulousCupcake** [codensity/gb-scripts#1]
Add [Impossible Omega II Raid](https://gbf.wiki/Impossible_Omega_II_Raids) translations.

Basic translation for these raids:
```
["シヴァ", "Shiva"],
["エウロペ", "Europa"],
["ゴッドガード・ブローディア", "Godsworn Alexiel"],
["ブローディア", "Alexiel"],
["グリームニル", "Grimnir"],
["メタトロン", "Metatron"],
["アバター", "Avatar"],
```

**Comment by codensity** [comment]
Thanks for the reminder. Added in https://github.com/codensity/codensity.github.io/commit/14a91f92cf525ecef93dcd991a50376640aa07a1.
